const translations = {
    ru: {
      "hero-title": "<strong>Здоровье</strong> — начинается<br><em>с правильной походки</em>",
      "hero-desc": "Mirai Smart Insole анализирует давление и походку в реальном времени, помогая выявить отклонения и восстановить баланс движений.",
      "cta-button": "Попробовать бесплатно",
      "problems-title": "Что мешает пациентам восстанавливаться быстрее?",
      "problems-subtitle": "Эти проблемы ежедневно встречаются в практике врачей и тренеров. Мы создаём инструмент, который упрощает диагностику и усиливает эффект терапии.",
      "technology-title": "Smart Insole: стельки нового поколения",
      "technology-desc": "Mirai Smart Insoles - это гибкие сенсорные стельки, которые измеряют данные и анализируют вашу походку в режиме реального времени.",
      "technology-button": "Смотреть демо",
      "how-title": "Как работает MIRAI Smart Insole?",
      "how-subtitle": "Всего 4 шага — и вы получаете цифровой портрет походки",
      "made-title": "In-house technology.<br />Made in Kazakhstan.",
      "made-description": "Каждая пара MIRAI Smart Insole создаётся на нашем производстве в Астане — от идеи до готового изделия. Это позволяет нам контролировать качество на всех этапах и внедрять инновации быстрее — от сенсоров до алгоритмов искусственного интеллекта.",
      "nav-about": "О нас",
      "nav-problem": "Проблема",
      "nav-solution": "Решение",
      "nav-tech": "Технологии",
      "nav-how": "Как работает MIRAI",
      "nav-metrics": "Метрики",
      "nav-service": "Применение",
      "nav-publications": "Публикации",
      "nav-blog": "Блог",
      "nav-news": "Новости",
      "nav-testimonials": "Отзывы",
      "nav-events": "События",
      "nav-contact": "Контакты",
      // Technology Section
      "technology-label": "Инновации в каждом шаге",
      "tech-feature-1-title": "ИИ-обработка данных",
      "tech-feature-1-text": "Автоматический анализ походки на базе алгоритмов машинного обучения.",
      "tech-feature-2-title": "Диагностика за 5 минут",
      "tech-feature-2-text": "Врачи получают объективную информацию уже во время первого приёма — больше не нужно тратить часы на наблюдение и субъективные тесты.",
      "tech-feature-3-title": "Объективная оценка прогресса",
      "tech-feature-3-text": "Вы больше не полагаетесь только на жалобы пациента. Теперь есть цифровые показатели, которые можно сравнивать от сессии к сессии.",
      "tech-feature-4-title": "Автоматический отчёт",
      "tech-feature-4-text": "Сокращает рутинную документацию. Специалисту остаётся только подписать и передать пациенту результат или сохранить в базе данных.",
      "tech-feature-5-title": "Непрерывный контроль вне клиники",
      "tech-feature-5-text": "Возможность отслеживать походку не только в клинике, но и дома, в спортзале или на улице. Наблюдение за динамикой пациента в реальных условиях.",
      "tech-feature-6-title": "Простой интерфейс для врачей и пациентов",
      "tech-feature-6-text": "Не требует обучения или специального оборудования. Всё запускается через приложение — на компьютере или телефоне.",
      // How Steps
      "how-step-1-title": "Установите стельки",
      "how-step-1-text": "Выберите нужный размер стельки и вставьте ее в обувь.",
      "how-step-2-title": "Подключитесь через Bluetooth",
      "how-step-2-text": "Запустите приложение и следуйте инструкциям на экране.",
      "how-step-3-title": "Пройдите 10 шагов",
      "how-step-3-text": "Стельки будут записывать ваши данные во время ходьбы.",
      "how-step-4-title": "Получите отчёт",
      "how-step-4-text": "Результаты вы можете сохранить, распечатать или отправить по почте.",
      // Metrics Section
      "metrics-title": "Метрики анализа походки",
      "metrics-subtitle": "Просматривайте ключевые данные о движении, давлении и симметрии шага.",
      "metric-1": "Асимметрия",
      "metric-2": "Длина шага",
      "metric-3": "Распределение нагрузки",
      "metric-4": "Динамика",
      "metric-5": "Фазы контакта",
      "metric-6": "Фазы переката",
      // Video Section
      "video-title": "Реальные шаги. Настоящие результаты.",
      "video-subtitle": "Диагностика, прогресс и контроль — всё наглядно в видеоформате.",
      // Service Section
      "service-title": "Применение",
      "service-subtitle": "Мы меняем подход к реабилитации и мониторингу движений. MIRAI TECH интегрируется в любые условия — от клиник и спортивных центров до домашних тренировок. Это — универсальный инструмент, который работает на результат.",
      // Cards
      "card-sport-title": "MIRAI TECH<br><span>в спорте</span>",
      "card-sport-text": "Используется для анализа походки и распределения нагрузки у профессиональных спортсменов.<br>Помогает скорректировать технику и предотвратить травмы.",
      "card-rehab-title": "MIRAI TECH<br><span>в клиниках и реабилитации</span>",
      "card-rehab-text": "Врачи используют стельки <br>для объективной оценки состояния пациента и адаптации реабилитационных программ.",
      // Publications & Testimonials
      "publications-title": "Наши публикации",
      "testimonials-title": "Отзывы",
      "testimonial-1-name": "Роман Иванов",
      "testimonial-1-role": "Золотой медалист Азиатских игр по лыжному фристайлу",
      "testimonial-1-text": "“Четко увидел разницу нагрузки по ногам, понял, над чем надо работать после интерпретации результатов врачом.”",
      "testimonial-2-name": "Таисия Дураченко",
      "testimonial-2-role": "Врач спортивной медицины и реабилитации<br>CEO",
      "testimonial-2-text": "“Теперь можно не только полагаться на впечатления пациента, но и демонстрировать объективные данные прогресса.”",
      "testimonial-3-name": "Мөлдір, 30 лет",
      "testimonial-3-role": "Офисный работник, домашний пользователь",
      "testimonial-3-text": "“Я взяла стельки для профилактики — хотела узнать, почему устаёт спина. И оказалось, что у меня перекос походки. Я даже пошла к остеопату с отчётом! Сейчас делаю простые упражнения, которые посоветовали в клинике, и чувствую, как стало легче.”",
      "testimonial-4-name": "Болат, 65 лет",
      "testimonial-4-role": "Пациент после инсульта",
      "testimonial-4-text": "“После инсульта у меня была проблема с равновесием и асимметрией походки. Mirai Tech Smart Insoles показали это сразу. Теперь врач корректирует программу реабилитации на основе конкретных цифр — и мне реально стало легче ходить.”",
      // News Section
      "news-title": "Новости",
      "news-1-title": "Digital Business",
      "news-1-desc": "Инженеры из Назарбаев Университета основали стартап Mirai Tech после обучения в Японии.",
      "news-1-link": "Подробнее →",
      "news-2-title": "The Steppe",
      "news-2-desc": "MIRAI TECH — стартап, меняющий подход к реабилитации в медицине и спорте.",
      "news-2-link": "Подробнее →",
      "news-3-title": "Forbes Kazakhstan",
      "news-3-desc": "Проект MIRAI TECH студентов и профессоров SEDS.",
      "news-3-link": "Подробнее →",
      "news-4-title": "Startup Voice",
      "news-4-desc": "Посмотрите видео с демонстрацией результатов анализа походки.",
      "news-4-link": "Смотреть →",
      "news-5-title": "TechCrunch",
      "news-5-desc": "Инновации MIRAI TECH в Instagram.",
      "news-5-link": "Смотреть →",
      "news-6-title": "MedTech Review",
      "news-6-desc": "Отзывы и аналитика MIRAI TECH в Instagram.",
      "news-6-link": "Смотреть →",
      "news-7-title": "TechCrunch",
      "news-7-desc": "Инновации в реабилитации с помощью стелек.",
      "news-7-link": "Смотреть →",
      "news-8-title": "TechCrunch",
      "news-8-desc": "AI и сенсоры от MIRAI TECH — взгляд на будущее.",
      "news-8-link": "Смотреть →",
      "news-9-title": "TechCrunch",
      "news-9-desc": "Результаты в движении: MIRAI TECH в действии.",
      "news-9-link": "Смотреть →",
      // Partners, Events, Preorder, Form, Footer
      "partners-subheading": "Партнеры",
      "events-title": "События",
      "preorder-subtitle": "Предзаказ",
      "preorder-title": "Получите умные стельки прямо сейчас",
      "form-name-placeholder": "Имя",
      "form-org-placeholder": "Организация",
      "form-email-placeholder": "Email",
      "form-phone-placeholder": "Телефон",
      "form-message-placeholder": "Сообщение",
      "form-button": "Оформить заказ",
      "form-success-title": "Заказ оформлен!",
      "form-success-text": "Спасибо за ваш заказ. Мы свяжемся с вами в ближайшее время.",
      "footer-description": "Технология MiraiTech разработана для лёгкой интеграции в повседневную жизнь.",
      "footer-contacts": "Контакты",
      "event-1-link": "Подробнее →",
      "event-2-link": "Подробнее →",
    },
    en: {
      "hero-title": "<strong>Health</strong> starts<br><em>with the right gait</em>",
      "hero-desc": "Mirai Smart Insole analyzes pressure and gait in real time to help detect deviations and restore movement balance.",
      "cta-button": "Try for free",
      "problems-title": "What prevents patients from recovering faster?",
      "problems-subtitle": "These problems are encountered daily by doctors and trainers. We are building a tool that simplifies diagnostics and strengthens therapy results.",
      "technology-title": "Smart Insole: Next Generation Insoles",
      "technology-desc": "Mirai Smart Insoles are flexible sensor insoles that measure data and analyze your gait in real time.",
      "technology-button": "Watch demo",
      "how-title": "How does MIRAI Smart Insole work?",
      "how-subtitle": "Only 4 steps — and you get a digital gait profile",
      "made-title": "In-house technology.<br />Made in Kazakhstan.",
      "made-description": "Each pair of MIRAI Smart Insole is made at our facility in Astana — from idea to finished product. This allows us to control quality at all stages and innovate faster — from sensors to AI algorithms.",
      "nav-about": "About Us",
      "nav-problem": "Problem",
      "nav-solution": "Solution",
      "nav-tech": "Technology",
      "nav-how": "How MIRAI Works",
      "nav-metrics": "Metrics",
      "nav-service": "Applications",
      "nav-publications": "Publications",
      "nav-blog": "Blog",
      "nav-news": "News",
      "nav-testimonials": "Testimonials",
      "nav-events": "Events",
      "nav-contact": "Contact",
      // Technology Section
      "technology-label": "Innovation in every step",
      "tech-feature-1-title": "AI-powered analysis",
      "tech-feature-1-text": "Automatic gait analysis based on machine learning algorithms.",
      "tech-feature-2-title": "Diagnosis in 5 minutes",
      "tech-feature-2-text": "Doctors receive objective information during the first appointment — no need for lengthy observations or subjective tests.",
      "tech-feature-3-title": "Objective progress tracking",
      "tech-feature-3-text": "You no longer rely only on the patient's words. Now you have digital indicators that can be compared from session to session.",
      "tech-feature-4-title": "Automatic reporting",
      "tech-feature-4-text": "Reduces routine documentation. The specialist only needs to sign and hand over the report or save it to the database.",
      "tech-feature-5-title": "Continuous monitoring outside clinic",
      "tech-feature-5-text": "Track gait not only in clinic, but also at home, gym, or outdoors. Monitor patient dynamics in real conditions.",
      "tech-feature-6-title": "Simple interface for doctors and patients",
      "tech-feature-6-text": "Requires no training or special equipment. Everything runs via the app — on desktop or phone.",
      // How Steps
      "how-step-1-title": "Insert the insoles",
      "how-step-1-text": "Choose the right size and place it in your shoe.",
      "how-step-2-title": "Connect via Bluetooth",
      "how-step-2-text": "Open the app and follow the on-screen instructions.",
      "how-step-3-title": "Take 10 steps",
      "how-step-3-text": "The insoles will record your data as you walk.",
      "how-step-4-title": "Get your report",
      "how-step-4-text": "You can save, print, or email the results.",
      // Metrics Section
      "metrics-title": "Gait Analysis Metrics",
      "metrics-subtitle": "View key data on motion, pressure, and step symmetry.",
      "metric-1": "Asymmetry",
      "metric-2": "Step Length",
      "metric-3": "Pressure Distribution",
      "metric-4": "Dynamics",
      "metric-5": "Contact Phases",
      "metric-6": "Roll Phases",
      // Video Section
      "video-title": "Real steps. Real results.",
      "video-subtitle": "Diagnostics, progress, and tracking — all shown in motion.",
      // Service Section
      "service-title": "Applications",
      "service-subtitle": "We change the approach to rehabilitation and motion monitoring. MIRAI TECH integrates into any environment — from clinics and sports centers to home workouts. A universal tool focused on results.",
      // Cards
      "card-sport-title": "MIRAI TECH<br><span>in sports</span>",
      "card-sport-text": "Used for analyzing gait and load distribution in professional athletes.<br>Helps correct technique and prevent injuries.",
      "card-rehab-title": "MIRAI TECH<br><span>in clinics and rehabilitation</span>",
      "card-rehab-text": "Doctors use the insoles <br>for objective assessment of patient condition and adapting rehabilitation programs.",
      // Publications & Testimonials
      "publications-title": "Our Publications",
      "testimonials-title": "Testimonials",
      "testimonial-1-name": "Roman Ivanov",
      "testimonial-1-role": "Asian Games Gold Medalist in Freestyle Skiing",
      "testimonial-1-text": "“Clearly saw the difference in leg load, understood what to work on after doctor’s interpretation.”",
      "testimonial-2-name": "Taisiya Durachenko",
      "testimonial-2-role": "Sports Medicine and Rehab Doctor<br>CEO",
      "testimonial-2-text": "“Now we can not only rely on the patient's words but also show objective progress data.”",
      "testimonial-3-name": "Moldir, 30 years old",
      "testimonial-3-role": "Office worker, home user",
      "testimonial-3-text": "“I took the insoles for prevention — I wanted to know why my back hurt. Turned out I had a gait imbalance. I even went to an osteopath with the report! Now I do simple exercises the clinic suggested, and I feel better.”",
      "testimonial-4-name": "Bolat, 65 years old",
      "testimonial-4-role": "Post-stroke patient",
      "testimonial-4-text": "“After my stroke, I had balance and gait issues. Mirai Tech Smart Insoles detected it right away. Now my doctor adjusts my rehab plan based on real numbers — and walking has really become easier.”",
      // News Section
      "news-title": "News",
      "news-1-title": "Digital Business",
      "news-1-desc": "Engineers from Nazarbayev University founded MIRAI TECH after studying in Japan.",
      "news-1-link": "Read more →",
      "news-2-title": "The Steppe",
      "news-2-desc": "MIRAI TECH — a startup transforming rehabilitation in medicine and sports.",
      "news-2-link": "Read more →",
      "news-3-title": "Forbes Kazakhstan",
      "news-3-desc": "MIRAI TECH project by SEDS professors and students.",
      "news-3-link": "Read more →",
      "news-4-title": "Startup Voice",
      "news-4-desc": "Watch a video showing gait analysis results.",
      "news-4-link": "Watch →",
      "news-5-title": "TechCrunch",
      "news-5-desc": "MIRAI TECH innovations on Instagram.",
      "news-5-link": "Watch →",
      "news-6-title": "MedTech Review",
      "news-6-desc": "Feedback and analysis from MIRAI TECH on Instagram.",
      "news-6-link": "Watch →",
      "news-7-title": "TechCrunch",
      "news-7-desc": "Rehabilitation innovations through insoles.",
      "news-7-link": "Watch →",
      "news-8-title": "TechCrunch",
      "news-8-desc": "AI and sensors by MIRAI TECH — a glimpse of the future.",
      "news-8-link": "Watch →",
      "news-9-title": "TechCrunch",
      "news-9-desc": "Results in motion: MIRAI TECH in action.",
      "news-9-link": "Watch →",
      // Partners, Events, Preorder, Form, Footer
      "partners-subheading": "Partners",
      "events-title": "Events",
      "preorder-subtitle": "Pre-Order",
      "preorder-title": "Get Smart Insoles Now",
      "form-name-placeholder": "Name",
      "form-org-placeholder": "Organisation Name",
      "form-email-placeholder": "Email",
      "form-phone-placeholder": "Phone",
      "form-message-placeholder": "Message",
      "form-button": "Make Pre-Order",
      "form-success-title": "Order Confirmed!",
      "form-success-text": "Thank you for your order. We will contact you shortly.",
      "footer-description": "MiraiTech technology is designed for seamless integration into daily life.",
      "footer-contacts": "Contacts",
      "event-1-link": "Read more →",
      "event-2-link": "Read more →",
    },
    kz: {
      "hero-title": "<strong>Денсаулық</strong><br><em>дұрыс жүруден басталады</em>",
      "hero-desc": "Mirai Smart Insole қысым мен жүрісті нақты уақытта талдап, ауытқуларды анықтауға және қозғалысты қалпына келтіруге көмектеседі.",
      "cta-button": "Тегін көру",
      "problems-title": "Пациенттердің тез қалпына келуіне не кедергі?",
      "problems-subtitle": "Бұл мәселелер дәрігерлер мен жаттықтырушылардың күнделікті тәжірибесінде кездеседі. Біз диагноз қоюды жеңілдететін және емдеу нәтижесін күшейтетін құрал жасаймыз.",
      "technology-title": "Smart Insole: жаңа буындағы стелькалар",
      "technology-desc": "Mirai Smart Insoles — бұл нақты уақытта жүрісіңізді өлшеп, талдайтын икемді сенсорлық стелькалар.",
      "technology-button": "Демонстрацияны көру",
      "how-title": "MIRAI Smart Insole қалай жұмыс істейді?",
      "how-subtitle": "Тек 4 қадам — және сіздің жүріс профиліңіз дайын",
      "made-title": "In-house технология.<br />Қазақстанда жасалған.",
      "made-description": "Әр MIRAI Smart Insole жұбы Астанадағы зауытымызда жасалады — идеядан дайын өнімге дейін. Бұл сапаны толық бақылауға және сенсорлардан бастап AI алгоритмдеріне дейін жылдам инновация жасауға мүмкіндік береді.",
      "nav-about": "Біз туралы",
      "nav-problem": "Мәселе",
      "nav-solution": "Шешім",
      "nav-tech": "Технология",
      "nav-how": "MIRAI қалай жұмыс істейді",
      "nav-metrics": "Метрикалар",
      "nav-service": "Қолдану саласы",
      "nav-publications": "Жарияланымдар",
      "nav-blog": "Блог",
      "nav-news": "Жаңалықтар",
      "nav-testimonials": "Пікірлер",
      "nav-events": "Оқиғалар",
      "nav-contact": "Байланыс",
      // Technology Section
      "technology-label": "Әр қадамдағы инновация",
      "tech-feature-1-title": "AI арқылы талдау",
      "tech-feature-1-text": "Машиналық оқыту алгоритмдеріне негізделген автоматты жүріс талдауы.",
      "tech-feature-2-title": "5 минутта диагностика",
      "tech-feature-2-text": "Дәрігерлер алғашқы қабылдау кезінде-ақ нақты мәлімет алады — бақылауға немесе субъективті тесттерге уақыт кетпейді.",
      "tech-feature-3-title": "Прогресті объективті бағалау",
      "tech-feature-3-text": "Пациенттің сөздеріне ғана сенудің қажеті жоқ. Енді сессия сайын салыстыруға болатын сандық көрсеткіштер бар.",
      "tech-feature-4-title": "Автоматты есеп",
      "tech-feature-4-text": "Күнделікті құжат жұмыстарын азайтады. Маман тек қол қойып, нәтижені пациентке береді немесе деректер базасына сақтайды.",
      "tech-feature-5-title": "Клиникадан тыс бақылау",
      "tech-feature-5-text": "Жүрісті тек клиникада ғана емес, үйде, спортзалда немесе көшеде бақылауға болады. Пациенттің нақты жағдайдағы динамикасын бақылау.",
      "tech-feature-6-title": "Қарапайым интерфейс",
      "tech-feature-6-text": "Оқыту немесе арнайы құрал қажет емес. Барлығы қосымша арқылы жұмыс істейді — компьютерде немесе телефонда.",
      // How Steps
      "how-step-1-title": "Стелькаларды салыңыз",
      "how-step-1-text": "Қажетті өлшемді таңдап, аяқ киімге салыңыз.",
      "how-step-2-title": "Bluetooth арқылы қосылыңыз",
      "how-step-2-text": "Қосымшаны ашып, экрандағы нұсқауларды орындаңыз.",
      "how-step-3-title": "10 қадам жасаңыз",
      "how-step-3-text": "Жүрген кезде стелькалар деректерді жазады.",
      "how-step-4-title": "Есепті алыңыз",
      "how-step-4-text": "Нәтижелерді сақтауға, басып шығаруға немесе пошта арқылы жіберуге болады.",
      // Metrics Section
      "metrics-title": "Жүріс талдау метрикалары",
      "metrics-subtitle": "Қозғалыс, қысым және қадам симметриясы туралы негізгі мәліметтерді көріңіз.",
      "metric-1": "Асимметрия",
      "metric-2": "Қадам ұзындығы",
      "metric-3": "Жүктеме таралуы",
      "metric-4": "Динамика",
      "metric-5": "Байланыс фазалары",
      "metric-6": "Ауыстыру фазалары",
      // Video Section
      "video-title": "Нақты қадамдар. Шынайы нәтиже.",
      "video-subtitle": "Диагностика, прогресс және бақылау — барлығы видеода көрсетіледі.",
      // Service Section
      "service-title": "Қолдану саласы",
      "service-subtitle": "Біз қалпына келтіру мен қозғалысты бақылауға жаңа көзқарас енгіземіз. MIRAI TECH кез келген жағдайда — клиникада, спортзалдарда және үй жаттығуларында қолданылады. Бұл — нәтижеге бағытталған әмбебап құрал.",
      // Cards
      "card-sport-title": "MIRAI TECH<br><span>спортта</span>",
      "card-sport-text": "Кәсіби спортшылардың жүрісін және жүктеме таралуын талдау үшін қолданылады.<br>Техниканы түзетуге және жарақаттардың алдын алуға көмектеседі.",
      "card-rehab-title": "MIRAI TECH<br><span>клиникада және оңалтуда</span>",
      "card-rehab-text": "Дәрігерлер пациенттің жағдайын объективті бағалап, оңалту бағдарламаларын бейімдеу үшін стелькаларды пайдаланады.",
      // Publications & Testimonials
      "publications-title": "Біздің жарияланымдар",
      "testimonials-title": "Пікірлер",
      "testimonial-1-name": "Роман Иванов",
      "testimonial-1-role": "Азия ойындарының фристайлдан алтын жүлдегері",
      "testimonial-1-text": "“Аяққа түскен салмақ айырмашылығын анық көрдім, нәтижелерді дәрігер түсіндіргеннен кейін не істеу керегін білдім.”",
      "testimonial-2-name": "Таисия Дураченко",
      "testimonial-2-role": "Спорттық медицина және оңалту дәрігері<br>CEO",
      "testimonial-2-text": "“Енді пациенттің сөзіне ғана емес, нақты прогресс деректерін көрсетуге де болады.”",
      "testimonial-3-name": "Мөлдір, 30 жаста",
      "testimonial-3-role": "Офистік қызметкер, үйде қолданушы",
      "testimonial-3-text": "“Мен стелькаларды алдын алу үшін алдым — арқа неге ауыратынын білгім келді. Жүрісімде ауытқу бар екен. Мен остеопатқа есеппен бардым! Қазір клиника ұсынған қарапайым жаттығуларды істеймін, жеңілдеп қалдым.”",
      "testimonial-4-name": "Болат, 65 жаста",
      "testimonial-4-role": "Инсульттен кейінгі пациент",
      "testimonial-4-text": "“Инсульттен кейін менде тепе-теңдік пен жүріс бұзылды. Mirai Tech Smart Insoles оны бірден анықтады. Енді дәрігер оңалту жоспарын нақты деректерге қарай түзетеді — жүру жеңілдеді.”",
      // News Section
      "news-title": "Жаңалықтар",
      "news-1-title": "Digital Business",
      "news-1-desc": "Назарбаев Университетінің инженерлері Жапонияда оқып келген соң Mirai Tech стартапын құрды.",
      "news-1-link": "Толығырақ →",
      "news-2-title": "The Steppe",
      "news-2-desc": "MIRAI TECH — медицина мен спорттағы оңалтуды өзгертетін стартап.",
      "news-2-link": "Толығырақ →",
      "news-3-title": "Forbes Kazakhstan",
      "news-3-desc": "SEDS профессорлары мен студенттерінің MIRAI TECH жобасы.",
      "news-3-link": "Толығырақ →",
      "news-4-title": "Startup Voice",
      "news-4-desc": "Жүріс анализінің нәтижесін бейнероликтен көріңіз.",
      "news-4-link": "Қарау →",
      "news-5-title": "TechCrunch",
      "news-5-desc": "MIRAI TECH Instagram-дағы инновациялар.",
      "news-5-link": "Қарау →",
      "news-6-title": "MedTech Review",
      "news-6-desc": "MIRAI TECH туралы пікірлер мен талдау.",
      "news-6-link": "Қарау →",
      "news-7-title": "TechCrunch",
      "news-7-desc": "Оңалтудың жаңа әдісі — стелькалармен.",
      "news-7-link": "Қарау →",
      "news-8-title": "TechCrunch",
      "news-8-desc": "MIRAI TECH жасаған AI және сенсорлар — болашаққа көзқарас.",
      "news-8-link": "Қарау →",
      "news-9-title": "TechCrunch",
      "news-9-desc": "Қозғалыстағы нәтиже: MIRAI TECH қалай жұмыс істейді.",
      "news-9-link": "Қарау →",
      // Partners, Events, Preorder, Form, Footer
      "partners-subheading": "Партнерлер",
      "events-title": "Оқиғалар",
      "preorder-subtitle": "Алдын ала тапсырыс",
      "preorder-title": "Ақылды стелькаларды дәл қазір алыңыз",
      "form-name-placeholder": "Аты-жөні",
      "form-org-placeholder": "Ұйым атауы",
      "form-email-placeholder": "Email",
      "form-phone-placeholder": "Телефон",
      "form-message-placeholder": "Хабарлама",
      "form-button": "Тапсырыс беру",
      "form-success-title": "Тапсырыс қабылданды!",
      "form-success-text": "Тапсырысыңыз үшін рахмет. Біз жақында сізбен хабарласамыз.",
      "footer-description": "MiraiTech технологиясы күнделікті өмірге оңай бейімделу үшін жасалған.",
      "footer-contacts": "Байланыс",
      "event-1-link": "Толығырақ →",
      "event-2-link": "Толығырақ →",
    }
  };
  
  function setLanguage(lang) {
    localStorage.setItem("lang", lang);
    document.querySelectorAll('[data-key]').forEach(el => {
      const key = el.getAttribute('data-key');
      if (translations[lang][key]) {
        el.innerHTML = translations[lang][key];
      }
    });
  }
  
  document.addEventListener("DOMContentLoaded", () => {
    const lang = localStorage.getItem("lang") || "ru";
    setLanguage(lang);
  });